#version 430 core

// 1グループ 64スレッド
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

// テクスチャ 4枚
layout(r32ui, binding = 0) uniform uimage3D gridIMX;
layout(r32ui, binding = 1) uniform uimage3D gridIMY;
layout(r32ui, binding = 2) uniform uimage3D gridIMZ;
layout(r32ui, binding = 3) uniform uimage3D gridIMA;

// 粒子のデータ構造
struct mpmParticle {
	vec4 position;		// 位置
	vec4 velocity;		// 速度 + padding
	mat4 affineC;		//アフィン速度行列 (mat3 分のみ値あり)
	mat4 deformation;	// 変形勾配 (mat3 分のみ値あり)

	// 砂の塑性変形パラメーター
	 float alpha;		//降伏面の大きさ
	 float q;			//硬化状態
	 float vc;			//変化の際の体積変化
	 int state;			//状態(変化)
	 int scale;			//スケール
	 int padding[3];		//調整
};

layout(std430, binding = 0) buffer mpmBuffer {
	mpmParticle p[];
};

// MPMの粒子群の物理パラメータ
layout(std140, binding = 1) uniform MPMPhysics {
	// シミュレーション空間
	vec3 gravity;		// 重力
	float timestep;		// 時間間隔
	vec3 f_normal;		// 地面の法線
	float f_height;		// 地面の高さ
	
	float f_restitution;// 地面の反発係数
	float f_friction;	// 地面の摩擦係数
	float dx;			// グリッドの間隔
	float inv_dx;		// 間隔の逆数

	// 粒子
	float p_restitution;// 粒子の反発係数
	float p_vol;		// 粒子の体積
	float p_mu;			// 粒子のラメ係数
	float p_lambda;		// 粒子のラメ係数

	float p_mass;		// 粒子の質量
	float p_radius;		// 粒子の半径
	float p_overlap;	// 粒子の重なり
	float p_padding;	// 調整
};

// AtomicAdd を Image にて行う
void atomicAddFloatX(ivec3 coords, float val) {
    uint oldVal = imageLoad(gridIMX, coords).x;
    uint newVal, expectedVal;
    do {
        expectedVal = oldVal;
        newVal = floatBitsToUint(uintBitsToFloat(expectedVal) + val);
        oldVal = imageAtomicCompSwap(gridIMX, coords, expectedVal, newVal);
    } while (oldVal != expectedVal);
}
void atomicAddFloatY(ivec3 coords, float val) {
    uint oldVal = imageLoad(gridIMY, coords).x;
    uint newVal, expectedVal;
    do {
        expectedVal = oldVal;
        newVal = floatBitsToUint(uintBitsToFloat(expectedVal) + val);
        oldVal = imageAtomicCompSwap(gridIMY, coords, expectedVal, newVal);
    } while (oldVal != expectedVal);
}
void atomicAddFloatZ(ivec3 coords, float val) {
    uint oldVal = imageLoad(gridIMZ, coords).x;
    uint newVal, expectedVal;
    do {
        expectedVal = oldVal;
        newVal = floatBitsToUint(uintBitsToFloat(expectedVal) + val);
        oldVal = imageAtomicCompSwap(gridIMZ, coords, expectedVal, newVal);
    } while (oldVal != expectedVal);
}
void atomicAddFloatA(ivec3 coords, float val) {
    uint oldVal = imageLoad(gridIMA, coords).x;
    uint newVal, expectedVal;
    do {
        expectedVal = oldVal;
        newVal = floatBitsToUint(uintBitsToFloat(expectedVal) + val);
        oldVal = imageAtomicCompSwap(gridIMA, coords, expectedVal, newVal);
    } while (oldVal != expectedVal);
}

// 固有値分解
void jacobiEigen(inout mat3 S, out mat3 V) {
    V = mat3(1.0);

	// 実用上は 3-5 回で十分 (3 を 5 に変えても可)
    for (int iter = 0; iter < 3; ++iter) {
        for (int p = 0; p < 2; ++p)
        for (int q = p + 1; q < 3; ++q) {

            float app = S[p][p];
            float aqq = S[q][q];
            float apq = S[p][q];

            if (abs(apq) < 1e-6) continue;

            float phi = 0.5 * atan(2.0 * apq, aqq - app);
            float c = cos(phi);
            float s = sin(phi);

            mat3 J = mat3(1.0);
            J[p][p] =  c; J[p][q] = s;
            J[q][p] = -s; J[q][q] = c;

            S = transpose(J) * S * J;
            V = V * J;
        }
    }
}

// 特異値分解
void svd(mat3 F, out mat3 U, out mat3 Sigma, out mat3 V) {
    mat3 S = transpose(F) * F;

    jacobiEigen(S, V);

    Sigma = mat3(0.0);
	// ゼロ除算の恐れがあるので、微小な値を足す(エプシロン)
    Sigma[0][0] = sqrt(max(S[0][0], 1e-4));
    Sigma[1][1] = sqrt(max(S[1][1], 1e-4));
    Sigma[2][2] = sqrt(max(S[2][2], 1e-4));

    mat3 invSigma = mat3(0.0);
    
	invSigma[0][0] = 1.0 / Sigma[0][0];
	invSigma[1][1] = 1.0 / Sigma[1][1];
	invSigma[2][2] = 1.0 / Sigma[2][2];

    U = F * V * invSigma;
}


void main() {
	uint idx = gl_GlobalInvocationID.x;
	if (idx >= p.length()) return;

	// 座標とインデックス計算
	vec3 x = p[idx].position.xyz;	// 粒子位置を獲得
	// 実成分の抽出
	vec3 v = p[idx].velocity.xyz;
	mat3 F = mat3(p[idx].deformation);
	mat3 C = mat3(p[idx].affineC);

	vec3 fx = x * inv_dx - 0.5;		// グリッドでの座標に変換 + 0.5 で座標1つ分後退して記録(探索ループにて使用)
	ivec3 base = ivec3(floor(fx));	// ボクセルでの基準となる座標
	vec3 weight_dist = fx - vec3(base);

	// 2次Bスプライン補間
	vec3 w[3];
	w[0] = 0.5 * pow( 1.5 - weight_dist, vec3(2.0));
	w[1] = 0.75 - pow( weight_dist - 1.0, vec3(2.0));
	w[2] = 0.5 * pow( weight_dist - 0.5, vec3(2.0));

	// 応力の計算 SVD(特異値分解)
	mat3 U, sig, V;
	svd(F, U, sig, V);

	mat3 e = mat3(0.0);
	e[0][0] = log( max(sig[0][0], 1e-6) );
	e[1][1] = log( max(sig[1][1], 1e-6) );
	e[2][2] = log( max(sig[2][2], 1e-6) );
	float trace_e = e[0][0] + e[1][1] + e[2][2];

	mat3 stress_diag = 2.0 * p_mu * e + p_lambda * trace_e * mat3(1.0);
	mat3 stress = U * stress_diag * transpose(V);	// Piola-Kirchoff応力の近似を扱う形式を利用(厳密にするなら strees_diag に inverse(sig) したものを掛けなければならない)
	// <追記> 厳密さを(人間の目にはわからない程度には)二の次にしているのでヤング率などで調整する方向性にする

	stress = (-p_vol * 4.0 * inv_dx * inv_dx) * stress * transpose(F);

	// グリッドへ転送
	mat3 affine = p_mass * C; // MLS_MPM
	for (int i=0; i<3; i++) {
		for (int j=0; j<3; j++) {
			for (int k=0; k<3; k++) {
				ivec3 offset = ivec3(i, j, k);
				ivec3 node_coords = base + offset;	// 今回の書き込み先
				if (any(lessThan(node_coords, ivec3(0))) || any(greaterThanEqual(node_coords, ivec3(128)))) {
					continue; // 範囲外のノードへの加算をスキップ
				}
				vec3 dpos = ( (vec3(offset) - weight_dist) * dx);
				float weight = w[i].x * w[j].y * w[k].z;	// Bスプラインは積

				// 運動量の加算 ( 質量 * 速度 + アフィン項 )
				vec3 mom_contrib = weight * (p_mass * v + affine * dpos);
				// 応力による力の加算
				vec3 force_contrib = weight * (stress * dpos);

				// 合計を AtomicAdd
				vec3 total_mom = mom_contrib + timestep * force_contrib;

				atomicAddFloatX(node_coords, total_mom.x);
                atomicAddFloatY(node_coords, total_mom.y);
                atomicAddFloatZ(node_coords, total_mom.z);
                atomicAddFloatA(node_coords, weight * p_mass);
			}
		}
	}
}
