#version 430 core

// 1グループ 64スレッド
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

// テクスチャ 4枚
layout(r32ui, binding = 0) uniform uimage3D gridIMX;
layout(r32ui, binding = 1) uniform uimage3D gridIMY;
layout(r32ui, binding = 2) uniform uimage3D gridIMZ;
layout(r32ui, binding = 3) uniform uimage3D gridIMA;

// 粒子のデータ構造
struct mpmParticle {
	vec4 position;		// 位置
	vec3 velocity;		// 速度
	mat3 affineC;		//アフィン速度行列
	mat3 deformation;	// 変形勾配

	// 砂の塑性変形パラメーター (未使用)
	 float alpha;		//降伏面の大きさ
	 float q;			//硬化状態
	 float vc;			//変化の際の体積変化
	 int state;			//状態(変化)

};

layout(std430, binding = 0) buffer mpmParticle {
	mpmParticle p[];
};

// 物理定数
layout(std140, binding = 1) uniform Physics {
	vec3 gravity;				// 重力
	float floor_height;			// 床の高さ
	vec3 floor_normal;			// 床の法線
	float floor_restitution;	// 床の反発
	float particle_restitution;	// 粒子の反発
	float mass;					// 粒子の質量
	float radius;				// 粒子の粒径
	float overlap;				// 粒子のかさなり
	float timestep;				// 時間間隔
	float inv_dx;				// dx:グリッド間隔
	float p_mu;					// 粒子のラメ係数 mu
	float p_lambda;				// 粒子のラメ係数 lambda
	float p_vol;				// 粒子 1 つあたりの体積
};

// AtomicAdd を Image にて行う
void imageAtomicAddFloat(layout(r32ui) uimage3D img, ivec3 coords, float val) {
	uint oldVal = imageLoad(img, coords).x;
	uint newVal, expectedVal;
	do {
		expectedVal = oldVal;
		float tmp = uintBitsToFloat(expectedVal);
		newVal = floatToUintBits(tmp + val);
		oldVal = imageAtomicCompSwap(img, coords, expectedVal, newVal);	// 今の値が expectedVal なら newVal に交換
	} while (oldVal != expectedVal);	// 他スレッドの割り込みがあれば再実行
}

void jacobiEigen(mat3 S, out mat3 V) {
    V = mat3(1.0);

	// 実用上は 3-5 回で十分 (3 を 5 に変えても可)
    for (int iter = 0; iter < 3; ++iter) {
        for (int p = 0; p < 2; ++p)
        for (int q = p + 1; q < 3; ++q) {

            float app = S[p][p];
            float aqq = S[q][q];
            float apq = S[p][q];

            if (abs(apq) < 1e-6) continue;

            float phi = 0.5 * atan(2.0 * apq, aqq - app);
            float c = cos(phi);
            float s = sin(phi);

            mat3 J = mat3(1.0);
            J[p][p] =  c; J[p][q] = s;
            J[q][p] = -s; J[q][q] = c;

            S = transpose(J) * S * J;
            V = V * J;
        }
    }
}

void svd(mat3 F, out mat3 U, out mat3 Sigma, out mat3 V) {
    mat3 S = transpose(F) * F;

    jacobiEigen(S, V);

    Sigma = mat3(0.0);
	// ゼロ除算の恐れがあるので、微小な値を足す(エプシロン)
    Sigma[0][0] = sqrt(max(S[0][0], 1e-6));
    Sigma[1][1] = sqrt(max(S[1][1], 1e-6));
    Sigma[2][2] = sqrt(max(S[2][2], 1e-6));

    mat3 invSigma = mat3(0.0);
    
	invSigma[0][0] = 1.0 / Sigma[0][0];
	invSigma[1][1] = 1.0 / Sigma[1][1];
	invSigma[2][2] = 1.0 / Sigma[2][2];

    U = F * V * invSigma;
}


void main() {
	uint idx = gl_GlobalInvocationID.x;
	if (idx >= p.length()) return;

	// 座標とインデックス計算
	vec3 x = p[idx].position.xyz;
	vec3 fx = x * inv_dx - 0.5;
	ivec3 base = ivec3(floor(fx));
	vec3 weight_dist = fx - vec3(base);

	// 2次Bスプライン補間
	vec3 w[3];
	w[0] = 0.5 * pow( 1.5 - weight_dist, vec3(2.0));
	w[1] = 0.75 - pow( weight_dist - 1.0, vec3(2.0));
	w[2] = 0.5 * pow( weight_dist - 0.5, vec3(2.0));

	// 応力の計算 SVD分解
	mat3 U, sig, V;
	svd(p[idx].deformation, U, sig, V);

	mat3 e = mat3(0.0);
	e[0][0] = log( max(sig[0][0], 1e-6) );
	e[1][1] = log( max(sig[1][1], 1e-6) );
	e[2][2] = log( max(sig[2][2], 1e-6) );
	float trace_e = e[0][0] + e[1][1] + e[2][2];

	mat3 stress_diag = 2.0 * p_mu * e + p_lambda * trace_e * mat3(1.0);
	mat3 stress = U * stress_diag * transpose(V);	// Piola-Kirchoff応力の近似を扱う形式を利用(厳密にするなら strees_diag に inverse(sig) したものを掛けなければならない)
	// <追記> 厳密さを(人間の目にはわからない程度には)二の次にしているのでヤング率などで調整する方向性にする

	stress = (-p_vol * 4.0 * inv_dx * inv_dx) * stress * transpose(p[idx].deformation);

	// グリッドへ転送
	mat3 affine = mass * p[idx].affineC; // MLS_MPM

	for (int i=0; i<3; i++) {
		for (int j=0; j<3; j++) {
			for (int k=0; k<3; k++) {
				ivec3 offset = ivec3(i, j, k);
				ivec3 node_coords = base + offset;
				vec3 dpos = ( (vec3(offset) - weight_dist) / inv_dx);
				float weight = w[i].x * w[j].y * w[k].z;	// Bスプラインでは積

				// 運動量の加算 ( 質量 * 速度 + アフィン項 )
				vec3 mom_contrib = weight * (mass * p[idx].velocity + affine * dpos);
				// 応力による力の加算
				vec3 force_contrib = weight * stress * dpos;

				// 合計を AtomicAdd
				vec3 total_mom = mom_contrib + timestep * force_contrib;

				imageAtomicAddFloat(gridIMX, node_coords, total_mom.x);
				imageAtomicAddFloat(gridIMY, node_coords, total_mom.y);
				// imageAtomicAddFloat(gridAtomicAddFloat(gridIMY, node_coords, total_mom.y));
				imageAtomicAddFloat(gridIMZ, node_coords, total_mom.z);
				imageAtomicAddFloat(gridIMA, node_coords, weight * mass);
			}
		}
	}
}
