#version 430 core

// 1グループ 64スレッド
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

// 粒子のデータ構造
struct mpmParticle {
	vec4 position;		// 位置
	vec4 velocity;		// 速度 + padding
	mat4 affineC;		//アフィン速度行列 (mat3 分のみ値あり)
	mat4 deformation;	// 変形勾配 (mat3 分のみ値あり)

	// 砂の塑性変形パラメーター
	 float alpha;		//降伏面の大きさ
	 float q;			//硬化状態
	 float vc;			//変化の際の体積変化
	 int state;			//状態(変化)
	 int scale;			//スケール
	 int padding[3];		//調整
};

layout(std430, binding = 0) readonly buffer ParticleBuffer { mpmParticle particle[]; };
layout(std430, binding = 1) writeonly buffer HistoryBuffer { mpmParticle history[]; };


uniform uint writeOffset;

void main() {
	uint idx = gl_GlobalInvocationID.x;
	if (idx >= particle.length()) return;

	// 現在の粒子状態を履歴バッファへ保存
	history[writeOffset + idx] = particle[idx];

}